# Generated by Django 5.0.4 on 2024-05-05 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_custom_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='AdminStaff_Profile',
        ),
        migrations.DeleteModel(
            name='Customer_Profile',
        ),
    ]
