# Generated by Django 5.0.4 on 2024-05-29 18:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_fav_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='fav_list',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
